# Generated by Django 5.0.3 on 2024-09-28 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0003_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
    ]
