# Generated by Django 5.0.3 on 2025-01-30 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0008_event_end_date_event_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
    ]
