# Generated by Django 5.0.3 on 2025-01-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0009_remove_event_end_date_remove_event_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('waiting', 'Aguardando Início'), ('active', 'Ativo'), ('closed', 'Encerrado (dia)'), ('finished', 'Finalizado')], default='paused', max_length=10),
        ),
    ]
