# Generated by Django 5.0.3 on 2025-02-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0011_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('waiting', 'Aguardando Início'), ('active', 'Ativo'), ('closed', 'Encerrado (dia)'), ('finished', 'Finalizado')], default='paused', max_length=10),
        ),
    ]
