# Generated by Django 5.0.3 on 2025-02-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0014_post_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='manual_override',
            field=models.BooleanField(default=False),
        ),
    ]
